"""Shared fixtures: synthetic OHLC bars with a known ground-truth volatility.

All estimator tests run offline against these; nothing in the test suite
touches the network.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

TRUE_ANNUAL_VOL = 0.32
ANNUALIZATION = 252
TRUE_DAILY_SIGMA = TRUE_ANNUAL_VOL / np.sqrt(ANNUALIZATION)


def simulate_ohlc(
    n_days: int = 1500,
    daily_sigma: float | np.ndarray = TRUE_DAILY_SIGMA,
    *,
    drift: float = 0.0,
    seed: int = 7,
    steps_per_day: int = 78,
    start: str = "2015-01-02",
) -> pd.DataFrame:
    """Simulate OHLC bars from a geometric Brownian motion with known volatility.

    The intraday path is generated at ``steps_per_day`` resolution so that the
    high and low are genuine path extrema -- range estimators are only unbiased
    against a continuously-observed path, and a two-point "range" would bias
    them badly low.  The full-day variance is ``daily_sigma**2``, split so the
    open-to-close session carries all of it and the overnight gap none, which
    matches what Parkinson/Garman-Klass/Rogers-Satchell actually measure.

    Args:
        n_days: Number of trading days to simulate.
        daily_sigma: Ground-truth daily volatility of the close-to-close return.
            Either a scalar (constant volatility) or a per-day array.
        drift: Per-day drift of the log price (tests Rogers-Satchell's
            drift-independence).
        seed: RNG seed.
        steps_per_day: Intraday steps used to form the high/low.
        start: First date of the business-day index.

    Returns:
        Frame indexed by business date with ``open``, ``high``, ``low``,
        ``close``, ``volume``.
    """
    rng = np.random.default_rng(seed)
    sigma = np.broadcast_to(np.asarray(daily_sigma, dtype="float64"), (n_days,))
    step_sigma = (sigma / np.sqrt(steps_per_day))[:, None]
    step_drift = drift / steps_per_day

    increments = rng.normal(step_drift, step_sigma, size=(n_days, steps_per_day))
    log_path = np.log(100.0) + np.cumsum(increments.ravel()).reshape(n_days, steps_per_day)

    opens = np.empty(n_days)
    opens[0] = np.log(100.0)
    opens[1:] = log_path[:-1, -1]  # no overnight gap: open == previous close

    full = np.concatenate([opens[:, None], log_path], axis=1)
    frame = pd.DataFrame(
        {
            "open": np.exp(full[:, 0]),
            "high": np.exp(full.max(axis=1)),
            "low": np.exp(full.min(axis=1)),
            "close": np.exp(full[:, -1]),
            "volume": rng.integers(1_000_000, 5_000_000, size=n_days).astype("float64"),
        },
        index=pd.bdate_range(start=start, periods=n_days, name="date"),
    )
    return frame


@pytest.fixture(scope="session")
def synthetic_ohlc() -> pd.DataFrame:
    """Zero-drift synthetic OHLC with ``TRUE_ANNUAL_VOL`` annualised volatility."""
    return simulate_ohlc()


@pytest.fixture(scope="session")
def synthetic_ohlc_drift() -> pd.DataFrame:
    """Synthetic OHLC with a strong upward drift, same diffusion volatility."""
    return simulate_ohlc(drift=0.0025, seed=11)


@pytest.fixture(scope="session")
def synthetic_ohlc_varying_vol() -> pd.DataFrame:
    """Synthetic OHLC whose volatility cycles between calm and stressed regimes.

    Constant-volatility paths are the wrong test bed for cross-estimator
    correlation: with no common signal to track, each estimator is pure noise
    around the same constant and the correlations collapse towards zero.  Real
    volatility moves, and it is that shared movement the estimators are
    supposed to agree on -- so the correlation test uses this fixture.
    """
    n_days = 1500
    cycle = np.sin(np.arange(n_days) * 2 * np.pi / 250.0)
    sigma = TRUE_DAILY_SIGMA * (1.0 + 0.6 * cycle)
    return simulate_ohlc(n_days=n_days, daily_sigma=sigma, seed=23)


@pytest.fixture
def small_ohlc() -> pd.DataFrame:
    """A short, hand-checkable OHLC frame."""
    return simulate_ohlc(n_days=60, seed=3)


# --------------------------------------------------------------------------- #
# Fixtures for the forecasting / evaluation layer (volmodels, voleval)
# --------------------------------------------------------------------------- #

TRUE_HAR_COEFFICIENTS = (0.0100, 0.35, 0.35, 0.25)  # intercept, daily, weekly, monthly


def simulate_har(
    coefficients: tuple[float, float, float, float] = TRUE_HAR_COEFFICIENTS,
    n_days: int = 3000,
    sigma: float = 0.010,
    *,
    in_logs: bool = False,
    seed: int = 17,
    start: str = "2010-01-04",
) -> pd.Series:
    """Simulate a series generated by a known one-step HAR process.

    Mirrors exactly the recursion :mod:`volmodels.har` estimates: the value at
    ``t+1`` is a linear function of the daily, weekly (5-day) and monthly
    (22-day) trailing averages ending at ``t``, plus Gaussian noise.  Estimating
    HAR on the output must therefore recover ``coefficients``.

    Args:
        coefficients: ``(intercept, beta_daily, beta_weekly, beta_monthly)``.
            The three betas should sum below 1 for stationarity.
        n_days: Length of the series.
        sigma: Innovation standard deviation.
        in_logs: Run the recursion in log space and exponentiate the result, so
            that ``LogHAR`` rather than ``HAR`` is the correctly-specified model.
        seed: RNG seed.
        start: First date of the business-day index.

    Returns:
        A strictly positive volatility series indexed by business day.
    """
    intercept, b_daily, b_weekly, b_monthly = coefficients
    rng = np.random.default_rng(seed)

    level = intercept / max(1e-6, 1.0 - (b_daily + b_weekly + b_monthly))
    values = np.full(n_days, level, dtype="float64")
    values[:22] += rng.normal(0.0, sigma, size=22)

    for t in range(21, n_days - 1):
        daily = values[t]
        weekly = values[t - 4 : t + 1].mean()
        monthly = values[t - 21 : t + 1].mean()
        values[t + 1] = (
            intercept
            + b_daily * daily
            + b_weekly * weekly
            + b_monthly * monthly
            + rng.normal(0.0, sigma)
        )

    series = pd.Series(
        values, index=pd.bdate_range(start=start, periods=n_days, name="date"), name="rv"
    )
    if in_logs:
        return np.exp(series)
    # Keep the levels-space series strictly positive without distorting its
    # dynamics: the simulation only dips near zero when sigma is large.
    return series.clip(lower=1e-4)


@pytest.fixture(scope="session")
def har_series() -> pd.Series:
    """Levels-space series generated by a known HAR process."""
    return simulate_har()


@pytest.fixture(scope="session")
def log_har_series() -> pd.Series:
    """Series whose *logarithm* follows a known HAR process."""
    return simulate_har(
        coefficients=(-0.0805, 0.35, 0.35, 0.25), sigma=0.10, in_logs=True, seed=29
    )


@pytest.fixture(scope="session")
def rv_series() -> pd.Series:
    """A short, realistic-looking RV series for harness tests."""
    return simulate_har(n_days=600, seed=5)
